import type { NextPage } from 'next'
import Head from 'next/head'
import styles from '../styles/Home.module.css'
import Spline from '@splinetool/react-spline'

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Spline className={styles.render} scene="https://prod.spline.design/kGMgvh8IL-oGyowa/scene.splinecode" />
    </div>
  )
}

export default Home
